---
- hosts: webservers
  become: true
  tasks:
    - name: downloading java
      yum:
        state: latest
    - name: installing OpenJdk
      yum:
        name: java-11
    - lineinfile:
        path: /etc/profile
        line: 'export JAVA_HOME=/usr/lib/jvm/jre-11-openjdk'
    - lineinfile:
        path: /etc/profile
        line:  'export JRE_HOME=/usr/lib/jvm/jre'
    - name: Installing list of packages of tomcat
      yum:
        name: "{{ packages }}"
      vars:
        packages:
          - tomcat
          - tomcat-webapps
          - tomcat-admin-webapps
          - tomcat-docs-webapp
          - tomcat-javadoc
        state: present
# *********************************FOR CHANGING PORT WE CAN DO IT IN 2 WAYS. STEP1: RUN THIS PLAYBOOK ONCE EXECUTED WE WILL GET ERROR BECAUSE SOURCE FILE IS NOT PRESENTED THEN GO TO ANY OF THE SERVER GET THE tomcat-users.xml (located in git under Playbooks repo with file name tomcat-users.xml) FILE COPY INTO CM AND ADD THE USERS STEP2: COPY THE tomcat-users.xml (located in git under Playbooks repo with file name tomcat-users.xml) FILE FROM INTERNET UPDATE THE ROLES AND RUN THIS COMMAND***********************************#

    - name: copying tomcat.users.xml file
      copy:
        src: /etc/ansible/playbooks/tomcat-users.xml
        dest: /usr/share/tomcat/conf/tomcat-users.xml
    - name: enabling tomcat service
      systemd:
        name: tomcat
        enabled: yes
    - name: starting tomcat service
      systemd:
        name: tomcat
        state: started
