---
- hosts: webservers
  become: true
  tasks:
    - name: updating CentOS7 System
      yum:
        name: "*"
        state: latest
    # *********************************INSTALLING JAVA***********************************
    - name: Downloading Java
      yum:
        state: latest
    - name: Installing OpenJdk
      yum:
        name: java-11
    - lineinfile:
        path: /etc/profile
        line: 'export JAVA_HOME=/usr/lib/jvm/jre-11-openjdk'
    - lineinfile:
        path: /etc/profile
        line: 'export JRE_HOME=/usr/lib/jvm/jre'
    # *********************************DOWNLOADING JENKINS REPO AND KEY***********************************
    - name: Downloading Jenkins Repo Jenkins
      get_url: url=https://pkg.jenkins.io/redhat-stable/jenkins.repo dest=/etc/yum.repos.d/jenkins.repo
    - name: Importing Jenkins Key
      rpm_key:
        state: present
        key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key
    - name: Installing jenkins
    # *********************************INSTALLING JENKINS***********************************
      yum:
        name: jenkins
        state: present
# *********************************FOR CHANGING PORT WE CAN DO IT IN 2 WAYS. STEP1: RUN THIS PLAYBOOK ONCE EXECUTED GO TO ANY OF THE SERVER GET THE JENKINS CONGIF FILE D=FROM /etc/sysconfig/jenkins (located in git under Playbooks repo with file name jenkins)  FILE COPY INTO CM AND CHANGE THE PORT AND RE-RUN THE PLAYBOOK SO THAT BELOW COPY COMMAND WILL REPLACE THE FILE INTO RM WITH UPDATED PORTNUMBER STEP2: COPY THE JENKINS FILE (located in git under Playbooks repo with file name jenkins) FROM INTERNET UPDATE THE PORT AND RUN THIS COMMAND***********************************#
    - name: copying jenkins file from CM to RM after updating a port number to 9090
      copy:
        src: /etc/ansible/playbooks/jenkins
        dest: /etc/sysconfig/jenkins
    - name: starting jenkins
      systemd:
        name: jenkins
        state: started
    - name: enable jenkins
      systemd:
        name: jenkins
        enabled: true
